### ISSUE TITLE
Release hexwalk_1.0.0a_Linux_x64.zip binary is not static.

### ISSUE THREAD

**Issue by malikcjm** [gcarmix/HexWalk#1]
When I tried to run hexwalk it failed with an error:
./hexwalk: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory

I run file command:
file ./hexwalk
and result was
./hexwalk: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), **dynamically linked**, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d4d26228b5013dee21fa547b1d94cf5fa42b9b65, for GNU/Linux 3.2.0, not stripped

result from ldd ./hexwalk

	linux-vdso.so.1 (0x00007ffc5797b000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0x00007f7e95bae000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007f7e95ba9000)
	libxcb-icccm.so.4 => /usr/lib/libxcb-icccm.so.4 (0x00007f7e95ba2000)
	libxcb-image.so.0 => /usr/lib/libxcb-image.so.0 (0x00007f7e95b9c000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007f7e95b97000)
	libxcb-keysyms.so.1 => /usr/lib/libxcb-keysyms.so.1 (0x00007f7e95b92000)
	libxcb-randr.so.0 => /usr/lib/libxcb-randr.so.0 (0x00007f7e95b7e000)
	libxcb-render-util.so.0 => /usr/lib/libxcb-render-util.so.0 (0x00007f7e95b78000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007f7e95b69000)
	libxcb-shape.so.0 => /usr/lib/libxcb-shape.so.0 (0x00007f7e95b63000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0x00007f7e95b5a000)
	libxcb-xfixes.so.0 => /usr/lib/libxcb-xfixes.so.0 (0x00007f7e95b51000)
	libxcb-xinerama.so.0 => /usr/lib/libxcb-xinerama.so.0 (0x00007f7e95b4a000)
	libxcb-xkb.so.1 => /usr/lib/libxcb-xkb.so.1 (0x00007f7e95b2b000)
	libxcb-xinput.so.0 => /usr/lib/libxcb-xinput.so.0 (0x00007f7e95b06000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f7e95adb000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f7e95998000)
	libSM.so.6 => /usr/lib/libSM.so.6 (0x00007f7e9598d000)
	libICE.so.6 => /usr/lib/libICE.so.6 (0x00007f7e9596d000)
	libxkbcommon-x11.so.0 => /usr/lib/libxkbcommon-x11.so.0 (0x00007f7e95964000)
	libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007f7e9591d000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f7e95903000)
	libicui18n.so.67 => not found
	libicuuc.so.67 => not found
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f7e958fc000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f7e95876000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f7e95871000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f7e95400000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f7e95784000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f7e9575f000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f7e95216000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f7e95bfa000)
	libxcb-util.so.1 => /usr/lib/libxcb-util.so.1 (0x00007f7e95756000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f7e95751000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f7e95749000)
	libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f7e95740000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f7e95686000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f7e951e4000)

It looks like only Qt library was statically linked into binary.

**Comment by gcarmix** [comment]
You are right, only the QT libraries are statically linked, system libraries are dynamically linked to avoid excessive file size, I tested the binary on Debian Linux and it worked seamlessy, what Linux distro did you use?

**Comment by malikcjm** [comment]
I'm using Arch Linux.

**Comment by malikcjm** [comment]
If it's like that by design, it means that this ticket can be closed.
