### ISSUE TITLE
'Open recent' does not work

### ISSUE THREAD

**Issue by learn-more** [gcarmix/HexWalk#10]
I have used HexWalk to open several files, but the 'Open Recent' menu stays empty.
Win10 22H2 19045.2965, HexWalk is started from a directory that is writable (but is not running as admin).

**Comment by learn-more** [comment]
> strange, I can't reproduce this one on Win 10. On my system when I open a file it is always added to the open recent tab, do you have another machine to try it on? I'll try on other PCs too

I figured it out:
- dragging a file from explorer onto HexWalk does not add it to the mru,
- opening the file from the menu does add it.

**Comment by gcarmix** [comment]
Correct, Thank you!! I'll fix in next release

**Comment by gcarmix** [comment]
resolved in 1.3.2
