### ISSUE TITLE
Cannot type an 'o' in the ascii column.

### ISSUE THREAD

**Issue by learn-more** [gcarmix/HexWalk#12]
Steps to reproduce:
- Start with a 'fresh' hexwalk (no file loaded)
- type some text in the 'ascii' column
- Try typing an 'o' (letter) in that column.
- The 'o' is not inserted, but the mode toggles between Insert/Overwrite
(The menu item accelerators are permanently underlined, maybe this is related?)

**Comment by gcarmix** [comment]
Nice catch, it is because the special key is incidentally also a key, I'll fix this in next release

**Comment by gcarmix** [comment]
resolved in 1.3.2
