### ISSUE TITLE
There is no indication that a file is opened

### ISSUE THREAD

**Issue by learn-more** [gcarmix/HexWalk#14]
When a file is initially opened, it is displayed in the status bar.
However, [after 2 seconds](https://github.com/gcarmix/HexWalk/blob/99f769c677ad68a1e88d33ab482756e0d3fa29d6/hexwalk/hexwalkmain.cpp#L309C55-L309C55) this text disappears, and there is no visual indication any more that we are editing a file.

**Comment by gcarmix** [comment]
I noticed this too, I'll fix in next release

**Comment by gcarmix** [comment]
resolved in 1.3.2
