### ISSUE TITLE
Silicon support

### ISSUE THREAD

**Issue by sonerfromnurland** [gcarmix/HexWalk#15]
Do you have a plan to release ARM version for Mac? You have released for intel chips of Mac. Can you release it for arms too?

**Comment by gcarmix** [comment]
Hi, at the moment I've no availability of M1 Macs to try, but in the future I surely can add it. Meanwhile have you tries with Rosetta?

**Comment by gcarmix** [comment]
I've tried the software on M1 and it works like charm, I think I can close this issue
