### ISSUE TITLE
Suggestion: Add `binwalk_windows` folder to Windows_X64 releases (in CI/CD pipeline)

### ISSUE THREAD

**Issue by TAbdiukov** [gcarmix/HexWalk#16]
The major gimmick of HexWalk is the ability is to use binwalk, not only on Windows, but in a pleasant GUI interface. There are many HEX editors available for Windows, but aforementioned binwalk is a key advantage of HexWalk

As Windows users will need to install binwalk binaries anyway to get HexWalk's binwalk running, it doesn't really make sense to have to clone the repo AND download the release. Ideally just 1 action should be required. Additionally, a novice user may get confused as to why compiled HexWalk keeps on loading infinitely even though it is fully compiled.

Therefore I suggest adding `binwalk_windows` folder to Windows_X64 releases (in CI/CD pipeline)

**Comment by gcarmix** [comment]
Issue solved in release 1.4.2
