### ISSUE TITLE
Cannot build on Linux Aarch64, static library error

### ISSUE THREAD

**Issue by blue-devil** [gcarmix/HexWalk#24]
Hello, I am trying to compile it from the source but I got an error:

```txt
/usr/bin/ld: attempted static link of dynamic object `/usr/lib/libQt5Charts.so'
collect2: error: ld returned 1 exit status
make: *** [Makefile:294: hexwalk] Error 1
```

My platform:
* OS: Archlinux
* `uname -r` : `5.19.4-1-aarch64-ARCH`

So, I am trying to compile this tool for aarch64 architecture. How can I compile
it dynamically for my platform?

Thank you

**Comment by gcarmix** [comment]
In hexwalk.pro try to comment out the following lines and let me know:

CONFIG += static
QMAKE_LFLAGS += -no-pie -lstdc++ -Bstatic -static-libgcc -static-libstdc++ -static

**Comment by blue-devil** [comment]
Hello, it worked thank you

![hexwalk lin arm](https://github.com/gcarmix/HexWalk/assets/10853207/35ad7752-78dd-4e1c-8484-ad493ba0e740)

#close #24

**Comment by gcarmix** [comment]
Good!
