### ISSUE TITLE
Mac: Cmd-F is bound to both "Edit >> Advanced Find" and "Analysis >> Entropy Map"

### ISSUE THREAD

**Issue by nicktimko** [gcarmix/HexWalk#26]
Cmd-F (analogous to Ctrl-F on Win/Linux) is apparently bound to both Advanced Find and Entropy Map, and when hitting Cmd-F, the entropy map seems to win. This is kinda surprising compared to the usual expectation of getting the Find tool in various apps.

Using 1.7.0 on macOS 14.3

**Comment by gcarmix** [comment]
You are absolutely right, just solved the issue, it will be included in next release,
Thank you!
