### ISSUE TITLE
QAction::event: Ambiguous shortcut overload: Ctrl+F

### ISSUE THREAD

**Issue by amurzeau** [gcarmix/HexWalk#27]
Hi,

Very nice hexeditor, that also support very large files :)

I tried the version 1.7.0 AppImage on Linux Debian Unstable and found that pressing Ctrl+F won't open the search dialog.
When pressing Ctrl+F, the console shows ` QAction::event: Ambiguous shortcut overload: Ctrl+F`.
Indeed, there is also the menu `Analysis->Entropy` with the Ctrl+F shortcut:
![image](https://github.com/gcarmix/HexWalk/assets/5435069/1085783c-b8a7-446a-af3d-adda2ef18d91)
![image](https://github.com/gcarmix/HexWalk/assets/5435069/9ff1f585-9779-4785-9c59-1a5c663d117a)

I'm more expecting the search dialog as Ctrl+F is commonly used for search in editors.

Thanks!

**Comment by gcarmix** [comment]
Thank you, solved in last release. Check it out👍
