### ISSUE TITLE
Pressing Escape on the Hash Calculator dialogbox doesn't stop the hashing

### ISSUE THREAD

**Issue by amurzeau** [gcarmix/HexWalk#28]
Hi,

I've found a (rather minor) issue with the Hash Calculator.

When having the Hash Calculator open on a big file, pressing Escape while it is still calculating the hash seems to not stop the hash calculation.
Pressing Escape while is was computing the hash does this:
- Close the Hash Calculator dialogbox
- The process is still at 100% CPU usage
- Closing HexWalk will close its window, but the process is still there at 100% CPU usage (I guess the process is waiting for the hashing completion)

Pressing the `Close` button does what I expected while pressing Escape:
- Close the Hash Calculator dialogbox
- The process' CPU usage goes back to 0%
- Closing HexWalk also stop the process

I'm using HexWalk AppImage v1.7.0 on Linux Debian Unstable.

Thanks!

**Comment by gcarmix** [comment]
Thank you, solved in 1.7.1 release👍
