### ISSUE TITLE
libicui18n.so.67: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thknx** [gcarmix/HexWalk#3]
```
user@ubuntu22-04:hexwalk_1.0.0a_Linux_x64$ ./hexwalk 
./hexwalk: error while loading shared libraries: **libicui18n.so.67: cannot open shared object file: No such file** or directory
```

Distro: Ubuntu 22.04-02

**Comment by gcarmix** [comment]
Yes, the software have a dependency of libicui18n, coming from QT, I'm working on to prepare a deb package addressing all this stuff, it should be ready in the next days, anyway in the meanwhile it should be enough to install libicu

**Comment by thknx** [comment]
Hi gcarmix,

libicu is already installed but I think there may be version mismatch.

**Comment by gcarmix** [comment]
hi @thknx, I have just released a new version of HexWalk, in the release you can find the .deb package. Install it with "dpkg -i hexwalk-1.1.0_amd64.deb". In case you get warnings of missing dependencies just run "sudo apt -f install" and it will download everything missing. I tried it on a fresh Ubuntu 22.04 and it works. Let me know if you solve.

**Comment by thknx** [comment]
It worked.
Thank you.
