### ISSUE TITLE
Little endian floats

### ISSUE THREAD

**Issue by amurzeau** [gcarmix/HexWalk#30]
Hi,

It seems that HexWalk decode floats as big endian.
Here is Okteta decoding the float as 3.42:
![image](https://github.com/gcarmix/HexWalk/assets/5435069/40c40c00-8b36-4ba8-9507-0a2029b04dcb)

And here HexWalk decode it as the number I would get as big endian in Okteta:
![image](https://github.com/gcarmix/HexWalk/assets/5435069/3a7fe20d-8a10-41ec-a11b-1130a297e9cb)

Okteta match what I expect while decoding raw little endian values (I encounter little endian more often than big endian).

I guess a solution is to add LE and BE for floats the same way there are LE/BE for Int.

Also, as an additional note, I found that when having a file with only 4 bytes, selecting the 4 bytes won't show me the float value, the 4th byte is not taken into account:
![image](https://github.com/gcarmix/HexWalk/assets/5435069/cd8b92f0-993d-40f7-8505-767e0ff018fe)
I can create a different issue for this if you prefer separating them.

**Comment by amurzeau** [comment]
Also, a 3rd note :)
Can floats be added to the "Number Converter" dialog (maybe with big/little endian too) ? Maybe it's not its purpose and I would be ok with that.

I encountered a case where I wanted to find the Hex bytes for a given float value.
So I used this instead: https://gregstoll.com/~gregstoll/floattohex/

**Comment by gcarmix** [comment]
@amurzeau Yes maybe the best would be to have both LE and BE for floats, I'll work on this and also on the bug, thank you

**Comment by gcarmix** [comment]
Solved with release v1.8.0
