### ISSUE TITLE
IntLE and IntBE are switched

### ISSUE THREAD

**Issue by Celant** [gcarmix/HexWalk#36]
It looks like the representations for Little-endian and Big-endian are reversed. According to multiple other hex editors, `c8f90500` is the Little-endian representation of `391624`, but HexWalk is showing it as Big-endian.

![image](https://github.com/gcarmix/HexWalk/assets/4339776/e41bb363-d2d4-44e0-bcc0-4f869b6a8db4)

**Comment by gcarmix** [comment]
You are right, I'm working to a new release and this bug will  be addressed in it, thank you!

**Comment by gcarmix** [comment]
Solved with release v1.8.0
