### ISSUE TITLE
No fullscreen on high resolution screen

### ISSUE THREAD

**Issue by EmilEmilchen** [gcarmix/HexWalk#37]
I'm using the application in Kubuntu under Wayland with a 4k screen. When fullscreening it the program takes up about 1/4th of the screen, I also cant resize it appropiatly. The scaling of text etc. works just fine. This really annoying and I'd love to know if theres a workaround.

**Comment by gcarmix** [comment]
I never tried it on a 4k screen, however thank you for spotting it, whenever I have the chance to try on 4k I'll fix it

**Comment by EmilEmilchen** [comment]
Starting in [v1.8.0](https://github.com/gcarmix/HexWalk/releases/tag/v1.8.0) this seems to be fixed!
