### ISSUE TITLE
Winodws 10 4k monitor with scale display error

### ISSUE THREAD

**Issue by YuriSizuku** [gcarmix/HexWalk#6]
Please fix this problem with higher dpi scale display and the maximum size button can't work. 

![image](https://github.com/gcarmix/HexWalk/assets/15275959/0e3ae3e3-df60-46f2-a4cb-1db77781c341)

**Comment by gcarmix** [comment]
Thank you for your report, I'll try to reproduce it and solve it as soon as possible

**Comment by gcarmix** [comment]
hi @YuriSizuku I should have resolved the scaling problem in release 1.2.1 that I just release, however I don't have a 4K monitor to try on, could you please let me know if it works?

**Comment by YuriSizuku** [comment]
Thank you very much.  I tested it and the text render is ok now.
